### ISSUE TITLE
Detects bound users when not logged in

### ISSUE THREAD

**Issue by cberger8** [idbind/idbs-demo-webapp#12]
App shows that there are "1688" bound users when nobody is logged in. May be an issue with how the array storing the users is initialized.

**Comment by cberger8** [comment]
Was an issue with rest calls getting 401ed and thus returning the html content of the login page rather than valid json. Made sure that said rest calls were not being performed when not authenticated. Resolved by 93c048398d4acabb83ed0603e1effbd0f18a4345.

**Comment by jricher** [comment]
You can also wire your API with a different Entry Point so that it never forwards to the login page on an error, but instead sends back a 403/401 response.
